### ISSUE TITLE
주말에는 안올라 왔으면 !

### ISSUE THREAD

**Issue by hueypark** [pythonkr/bots#4]

**Comment by Bloodevil** [comment]
개인적인 의견입니다. 강제하지는 않아요.
 - 전 주말에는 멘션만 안했으면 좋겠어요. 주중에 정신없어도 주말에 적어도 한번은 몰아보는데, 주말에 안올라오면 일타래 링크를 다시 찾아들어가야해서요.  그런걸로 '주말 플래그' 나 '멘션 플래그'를 둬서 본인이 셋팅할 수 있게 해주는건 어떨까요?

**Comment by hueypark** [comment]
1차적으로 주말에는 멘션만 안 하는 방향으로 작업합니다
