### ISSUE TITLE
데드라인이 많이 남았을때에는 좀 덜 귀찮게 했으면

### ISSUE THREAD

**Issue by hueypark** [pythonkr/bots#5]
- 데드라인이 많이 남았을때에는 좀 덜 귀찮게 했으면.. (D-1 에만 알려준다거나?)
- 데드라인이 많이 남았을 때에는 DM으로 보내는 방법도?

**Comment by Bloodevil** [comment]
데드라인이 많이 남았을땐 멘션없이 하루에 한번 리스팅만 해주고, 데드라인이 다가오면 (D-3이나 1 정도?) 멘션을 붙이는것도 괜찮겠네요.

**Comment by hueypark** [comment]
D-1부터 알려주는 방식으로 변경합니다
