### ISSUE TITLE
메시지가 한줄만 차지 했으면

### ISSUE THREAD

**Issue by hueypark** [pythonkr/bots#6]

**Comment by tebica** [comment]
아직 제가 단 양식은 없는데 이정도가 어떨까요?
> @tebica 님 D-3 입니다 : 일의 내용은 이것이당. 꼭해야한당 블라블라

**Comment by Bloodevil** [comment]
글자수를 정하는 정도가 어떨까요? 메시지가 한줄만 이라는게 좀 애매하니까요. 포멧을 정하는건 좋습니다!

**Comment by tebica** [comment]
일단 inactive 한 메시지가 자꾸 올라와서 슬랙이 스크롤이 되어서.. 보기 안좋아서요 ㅠㅜ
